oauth:
  client:
    jwt:
      clientsecret: c2VjcmV0
      clientid: bXBzYWRtaW51c2Vy
      clientidn: c2VjcmV0
      clientsecretn: bXBzYWRtaW51c2Vy
basic:
  auth:
    clientsecret: Basic c2FuZGVlcDpwYXNzd29yZA==
    clientusername: c2FuZGVlcA==
    clientpass: cGFzc3dvcmQ=
mps:
  oauth2:
    server:
      host: localhost
      port: 8081
      servletcontext: MPSOAuth2Server
      endpoint: oauth/token
      userendpoint: api/user
    defaultRoles:
      readId: 2
      readDesc: COMPANY_READ
kafka:
  bootstrap-servers: localhost:9092
  topic:
    helloworld: helloworld.t
  folder: D:\\Softwares\\JavaDownloads\\Sandeep\\Apache-Kafka\\kafka_2.11-1.0.0